server:
  port: 9192
spring:
  datasource:
    url: jdbc:mysql://db-1:3306/my_database
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
